@startuml
left to right direction
skinparam packageStyle rectangle
actor "Автор статьи" as User
    usecase "Войти в систему" as UC_Login
    usecase "Отправить статью" as UC_Send
actor "Читатель" as User2
    usecase "Войти в систему" as UC_Login2
    usecase "Вывести статьи" as UC_Vivod
    usecase "Прочитать статью" as UC_Read
    usecase "Найти статью" as UC_Find
    usecase "Оценить статью" as UC_Rate
actor "Админ" as User3
    usecase "Войти в систему" as UC_Login3
    usecase "Работать со статьями" as UC_Work
    usecase "Удалить статью" as UC_Del
    usecase "Добавить статью" as UC_Dob
    usecase "Отклонить статью" as UC_Den
User -- UC_Login
UC_Login -- UC_Send
User2 -- UC_Login2
UC_Login2 -- UC_Read
UC_Read ..> UC_Find: <<extend>>
UC_Read ..> UC_Rate: <<extend>>
User3 -- UC_Login3
UC_Login3 -- UC_Work
UC_Work -- UC_Vivod
UC_Vivod ..> UC_Del: <<extend>>
UC_Vivod ..> UC_Den: <<extend>>
UC_Vivod ..> UC_Dob: <<extend>>
@enduml
